# Include CI/CD templates
include:
  - project: "sysadm-k8s/helmfile-templates"
    ref: "master"
    file: "gitlab-ci-template.yml"

.k8s_base_domain: &k8s_base_domain gcp-k8s-accelerator-prod.srv.local

variables:
  app_name: accelerator-api

stages:
  - linting
  - testing
  - build_docker
  - deploy
  - cleanup
  - deploy_current

lint:
  image: node:16.13.0-alpine3.14
  stage: linting
  script:
    - npm install
    - npm run lint
  artifacts:
    paths:
      - node_modules/
  tags:
    - devops
  only:
    - branches

test:
  image: node:16.13.0-alpine3.14
  stage: testing
  script:
    - npm run test
  tags:
    - devops
  only:
    - branches

build image:
  extends:
    - .helm_ci_templates_build_docker_image
  variables:
    GIT_STRATEGY: clone
    docker_image: ${docker_registry_host}/ci/accelerator-api:${CI_COMMIT_REF_SLUG}
  dependencies: []
  needs: []

### STAGE ###
deploy to stage: # Scheduled stop after 1d by default
  extends:
    - .helm_ci_templates_deploy_to_stage

stop on stage:
  extends:
    - .helm_ci_templates_stop_on_stage

stop on stage cleanup: # Auto stop if deployment fails
  extends:
    - .helm_ci_templates_stop_on_stage_cleanup

current on stage:
  extends:
    - .helm_ci_templates_current_on_stage

### PROD ###
deploy to prod:
  extends:
    - .helm_ci_templates_deploy_to_prod
  variables:
    k8s_base_domain: *k8s_base_domain

stop on prod: # Scheduled stop after 1d by default
  extends:
    - .helm_ci_templates_stop_on_prod

stop on prod cleanup: # Auto stop if deployment fails
  extends:
    - .helm_ci_templates_stop_on_prod_cleanup

current on prod:
  extends:
    - .helm_ci_templates_current_on_prod
  variables:
    k8s_base_domain: *k8s_base_domain
